version: '3'

vars:
  # Docker Compose
  COMPOSE_DIR: .docker/compose
  DBMATE_DIR: .db/migrations

silent: true

tasks:
  compose-stop:
    desc: Stops docker-compose containers
    dir: "{{ .COMPOSE_DIR }}"
    cmds:
      - docker-compose kill -s SIGTERM > /dev/null 2>&1 || echo "There are no running containers..."
      - docker wait $(docker-compose ps -a -q) || echo "There are no existing containers..."

  compose-run:
    desc: Runs docker-compose
    dir: "{{ .COMPOSE_DIR }}"
    cmds:
      - task: compose-stop
      - docker-compose up -d

  db-dump:
    desc: Dumps DB schema
    cmds:
      - dbmate -d {{ .DBMATE_DIR }} dump

  db-migrate:
    desc: Migrates DB schema
    cmds:
      - dbmate -d {{ .DBMATE_DIR }} up